version: "3"

server:
  command: "php app.php"

http:
  address: 0.0.0.0:8080
  middleware: [gzip]
  pool:
    num_workers: 1
    #max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "./"
    forbid: [".php"]
    mime_types:
      css: "text/css"
      js: "text/javascript"
      png: "image/png"
      jpg: "image/jpeg"
      jpeg: "image/jpeg"
      gif: "image/gif"
      svg: "image/svg+xml"
      ico: "image/x-icon"
      json: "application/json"
      woff: "font/woff"
      woff2: "font/woff2"
      ttf: "font/ttf"
      mp4: "video/mp4"
      webm: "video/webm"
      mp3: "audio/mpeg"
